exclude: |
    (?x)(
        /build/
    )

repos:
-   repo: https://github.com/Lucas-C/pre-commit-hooks
    rev: v1.5.5
    hooks:
     -  id: insert-license
        files: \.py|\.sh$
        args:
            - --license-filepath
            - .pre-commit-license-header.txt
            - --allow-past-years
            - --no-extra-eol
     -  id: insert-license
        files: \.java$
        args:
            - --license-filepath
            - .pre-commit-license-header.txt
            - --comment-style
            - //
            - --use-current-year
            - --allow-past-years
            - --no-extra-eol
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
    -   id: check-yaml
        args: [--allow-multiple-documents]
    -   id: trailing-whitespace
        exclude: '\.diff$'
        args: [--markdown-linebreak-ext=md]
    -   id: check-added-large-files
        args: ['--maxkb=1024']
    -   id: check-merge-conflict
    -   id: detect-aws-credentials
        args: [--allow-missing-credentials]
    -   id: end-of-file-fixer
        exclude: |
            (?x)(
                \.diff$
            )
    -   id: fix-byte-order-marker
-   repo: https://github.com/rhysd/actionlint
    rev: v1.7.7
    hooks:
    -   id: actionlint
# SC2028: Use printf instead of echo
# SC2129: Consider using { cmd1; cmd2; } >> file instead of individual redirects.
        args: ['-ignore', 'SC2028', '-ignore', 'SC2129']
-   repo: https://github.com/shellcheck-py/shellcheck-py
    rev: v0.10.0.1
    hooks:
    -   id: shellcheck
        exclude: '\.yml$'
-   repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.13.0
    hooks:
    -   id: ruff-check
        name: Ruff check
        args: [--fix]
    -   id: ruff-format
        name: Ruff format
-   repo: https://github.com/jsh9/pydoclint
    rev: 0.7.3
    hooks:
    -   id: pydoclint
        args: [--quiet]
        files: ^qai_hub_models/(configs|datasets)/.*
-   repo: local
    hooks:
    -   id: mypy
        name: mypy
        files: qai_hub_models/.*(py|pyi|ipynb)$
        exclude: qai_hub_models/models/_internal/.*
        entry: scripts/util/run_mypy.sh
        language: system
        # By default, precommit will split the files into groups and run
        # mypy on each group in parallel. This causes mypy to miss issues
        # and/or dump the failure several times.
        #
        # This flag makes precommit run mypy once on all files.
        require_serial: true
